//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <arpa/inet.h>
#include <netinet/in.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <sys/socket.h>
#include <windows.h>

// ------------------------ Structures ------------------------

struct WSAData {
    int16_t e0;
    int16_t e1;
    int16_t e2;
    int16_t e3;
    char * e4;
    char e5[1];
    char e6[1];
};

struct sockaddr {
    int16_t e0;
    char e1[14];
};

// ------------------- Function Prototypes --------------------

int32_t entry_point(void);
int32_t function_401008(int32_t a1);
int32_t function_401121(char * buf);
int32_t function_4011e6(char * a1, int32_t a2, int32_t a3, int32_t a4);

// --------------------- Global Variables ---------------------

int32_t g1 = 0; // ebx
int32_t g2 = 0; // edi
int32_t g3 = 0; // esi
int32_t g4 = 0x2b6a006a; // 0x4010f5

// ------------------------ Functions -------------------------

// Address range: 0x401000 - 0x401007
int32_t entry_point(void) {
    // 0x401000
    int32_t v1;
    function_401008(v1);
    return 0;
}

// Address range: 0x401008 - 0x401120
int32_t function_401008(int32_t a1) {
    int32_t v1;
    int32_t sock = function_401121((char *)&v1); // 0x401015
    if (sock == 0) {
        // 0x401118
        // branch -> 0x40111a
    } else {
        int32_t v2 = 0x40107c; // eax
        int32_t v3 = 0x40107c; // 0x401040
        // branch -> 0x401039
        while (true) {
            char * v4 = (char *)v3; // 0x401039_0
            int32_t v5 = 0x1000000 * ((int32_t)*v4 ^ v1 & 255) / 0x1000000;
            int32_t v6 = v5 + 34; // 0x40103d
            g1 = v6 & 255 | v5 & -256;
            *v4 = (char)v6;
            int32_t v7 = v2 + 1; // 0x401042
            v2 = v7;
            if (v7 >= (int32_t)&g4) {
                int32_t v8 = function_4011e6((char *)0x40107c, 121, g2, g3) & 0xffff; // 0x40105b
                v2 = v8;
                int32_t result;
                if (v8 != 0xfb5e) {
                    // 0x401065
                    send(sock, "Nope, that's not it.", 20, 0);
                    // branch -> 0x401107
                    // 0x401107
                    closesocket(sock);
                    result = WSACleanup();
                    // branch -> 0x40111a
                    // 0x40111a
                    return result;
                }
                unsigned char v9 = *(char *)(g2 + 0x61791c4); // 0x401085
                int32_t v10 = (int32_t)v9 ^ *(int32_t *)0x1681068a; // ebx
                int32_t * v11 = (int32_t *)(8 * g3 + 0xfb5e); // 0x40108b_0
                uint32_t v12 = *v11; // 0x40108b
                *v11 = v12 - 0xeea7efa;
                int32_t v13 = 120; // 0x401098
                int32_t * v14; // 0x4010a2_0
                int32_t * v15; // 0x4010b0_0
                int32_t * v16; // 0x4010b8_0
                int32_t * v17; // 0x4010bf_0
                int32_t * v18; // 0x4010cf_0
                int32_t * v19; // 0x4010d6_0
                int32_t * v20; // 0x4010de_0
                int32_t * v21; // 0x4010e6_0
                int32_t * v22; // 0x4010ee_0
                int32_t v23; // edx
                int32_t v24; // 0x4010a8
                if (v13 != 0) {
                    // 0x4010a0
                    v14 = (int32_t *)g3;
                    *v14 = (int32_t)(v12 > 0xeea7ef9) - 0x1f99c4f0 + *v14;
                    v24 = *(int32_t *)(v13 + 0x1d81061c);
                    v23 = v24;
                    v15 = (int32_t *)(v24 - 17);
                    *v15 = *v15 & -0xd9c7efa;
                    v16 = (int32_t *)(v2 - 29);
                    *v16 = *v16 & 0x66199c4;
                    v17 = (int32_t *)(g3 - 68);
                    *v17 = *v17 & -0x19987efa;
                    v18 = (int32_t *)(v23 - 14);
                    *v18 = *v18 - 0x66b99c4;
                    v19 = (int32_t *)(v2 - 87);
                    *v19 = *v19 + 0x10967efa;
                    v20 = (int32_t *)(g3 - 18);
                    *v20 = *v20 + 0x51907efa;
                    v21 = (int32_t *)(v10 + 6);
                    *v21 = *v21 - 0x6ef6d81;
                    v22 = (int32_t *)(v23 - 23);
                    *v22 = *v22 ^ 0x7c738106;
                    send(sock, "Congratulations! But wait, where's my flag?", 43, 0);
                    // branch -> 0x401107
                    // 0x401107
                    closesocket(sock);
                    result = WSACleanup();
                    // branch -> 0x40111a
                    // 0x40111a
                    return result;
                }
                int32_t * v25 = (int32_t *)v2; // 0x40109a_0
                uint32_t v26 = *v25; // 0x40109a
                int32_t v27 = v26 - 0x198106f2; // 0x40109a
                bool v28 = v12 > 0xeea7ef9 ? v26 < v27 + (int32_t)(v12 > 0xeea7ef9) : v26 < 0x198106f2; // 0x40109a
                *v25 = v27 + (int32_t)(v12 > 0xeea7ef9);
                // branch -> 0x4010a0
                // 0x4010a0
                v14 = (int32_t *)g3;
                *v14 = (int32_t)v28 - 0x1f99c4f0 + *v14;
                v24 = *(int32_t *)(v13 + 0x1d81061c);
                v23 = v24;
                v15 = (int32_t *)(v24 - 17);
                *v15 = *v15 & -0xd9c7efa;
                v16 = (int32_t *)(v2 - 29);
                *v16 = *v16 & 0x66199c4;
                v17 = (int32_t *)(g3 - 68);
                *v17 = *v17 & -0x19987efa;
                v18 = (int32_t *)(v23 - 14);
                *v18 = *v18 - 0x66b99c4;
                v19 = (int32_t *)(v2 - 87);
                *v19 = *v19 + 0x10967efa;
                v20 = (int32_t *)(g3 - 18);
                *v20 = *v20 + 0x51907efa;
                v21 = (int32_t *)(v10 + 6);
                *v21 = *v21 - 0x6ef6d81;
                v22 = (int32_t *)(v23 - 23);
                *v22 = *v22 ^ 0x7c738106;
                send(sock, "Congratulations! But wait, where's my flag?", 43, 0);
                // branch -> 0x401107
                // 0x401107
                closesocket(sock);
                result = WSACleanup();
                // branch -> 0x40111a
                // 0x40111a
                return result;
            }
            // 0x401039
            v3 = v7;
            // branch -> 0x401039
        }
    }
    // 0x40111a
    int32_t v29;
    return &v29;
}

// Address range: 0x401121 - 0x4011e5
int32_t function_401121(char * buf) {
    int32_t v1;
    if (WSAStartup(514, (struct WSAData *)&v1) == 0) {
        int32_t v2 = g3; // 0x401147
        int32_t v3 = g2; // 0x401148
        int32_t sock_fd = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP); // 0x401151
        if (sock_fd != -1) {
            int32_t addr = 2;
            inet_addr("127.0.0.1");
            htons(2222);
            if (bind(sock_fd, (struct sockaddr *)&addr, 16) != -1) {
                // 0x401191
                if (listen(sock_fd, 0x7fffffff) != -1) {
                    int32_t accepted_sock_fd = accept(sock_fd, NULL, NULL); // 0x4011a7
                    if (accepted_sock_fd != -1) {
                        int32_t result = accepted_sock_fd;
                        if (recv(accepted_sock_fd, buf, 4, 0) < 1) {
                            // 0x4011ca
                            closesocket(accepted_sock_fd);
                            // branch -> 0x4011d1
                            // 0x4011d1
                            closesocket(sock_fd);
                            // branch -> 0x4011d8
                            // 0x4011d8
                            WSACleanup();
                            result = 0;
                            // branch -> 0x4011e0
                        }
                        // 0x4011e0
                        g2 = 0x10000 * v3 / 0x10000;
                        g3 = v2;
                        // branch -> 0x4011e2
                        // 0x4011e2
                        return result;
                    }
                }
            }
            // 0x4011d1
            closesocket(sock_fd);
            // branch -> 0x4011d8
        }
        // 0x4011d8
        WSACleanup();
        // branch -> 0x4011e0
        // 0x4011e0
        g2 = 0x10000 * v3 / 0x10000;
        g3 = v2;
        // branch -> 0x4011e2
    }
    // 0x4011e2
    return 0;
}

// Address range: 0x4011e6 - 0x40126b
int32_t function_4011e6(char * a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x4011e6
    int32_t v1; // 0x40124e
    uint32_t v2; // 0x40125a_0
    if (a2 == 0) {
        v1 = 255;
        v2 = 255;
        // 0x40124a
        return v2 / 256 + (v2 & 255) | 256 * v1 + (v1 & 0xff00);
    }
    int32_t v3 = g2; // 0x4011fe
    int32_t v4 = 255; // 0x40121925
    int32_t v5 = (int32_t)a1; // 0x40120f22
    int32_t v6 = v3; // 0x401202
    int32_t v7 = 255; // 0x401202_0
    // branch -> 0x401202
    int32_t v8;
    int32_t v9; // 0x40123a
    while (true) {
        int32_t v10 = a2 > 20 ? 20 : a2; // 0x40120d
        uint32_t v11 = -1 - a2;
        int32_t v12 = v10; // 0x40121d
        int32_t v13 = v6 & -0x10000 | v7; // 0x401212
        int32_t v14 = v5; // 0x40121c
        uint32_t v15 = (int32_t)*(char *)v14 + v13; // 0x401212
        int32_t v16 = v13 & -0x10000; // 0x401212
        int32_t v17 = 0x10000 * v15 / 0x10000; // 0x401215_0
        int32_t v18 = v17 + v4; // 0x401219
        // branch -> 0x40120f
        while (v12 != 1) {
            // 0x40120f
            v12--;
            v13 = v15 & 0xffff | v16;
            v14++;
            v15 = (int32_t)*(char *)v14 + v13;
            v16 = v13 & -0x10000;
            v17 = 0x10000 * v15 / 0x10000;
            v18 += v17;
            // continue -> 0x40120f
        }
        int32_t v19 = v15 / 256 & 255; // 0x401226
        v8 = (v17 & 255) + v19 & 511;
        v9 = (v18 / 256 & 255) + (v18 & 255);
        if (a2 == v10) {
            // break -> 0x401247
            break;
        }
        v4 = v9;
        v5 = v5 - 1 - (v11 > 0xffffffeb ? v11 : -21);
        a2 -= v10;
        v6 = v19 | v16;
        v7 = v8;
        // continue -> 0x401202
    }
    // 0x401247
    g2 = v3;
    v1 = v9;
    v2 = v8;
    // branch -> 0x40124a
    // 0x40124a
    return v2 / 256 + (v2 & 255) | 256 * v1 + (v1 & 0xff00);
}

// --------------- Dynamically Linked Functions ---------------

// SOCKET accept(_In_ SOCKET s, struct sockaddr * addr, _Inout_opt_ int * addrlen);
// int bind(_In_ SOCKET s, const struct sockaddr * name, _In_ int namelen);
// int closesocket(_In_ SOCKET s);
// u_short htons(_In_ u_short hostshort);
// unsigned long inet_addr(_In_z_ const char * cp);
// int listen(_In_ SOCKET s, _In_ int backlog);
// int recv(_In_ SOCKET s, char * buf, _In_ int len, _In_ int flags);
// int send(_In_ SOCKET s, const char * buf, _In_ int len, _In_ int flags);
// SOCKET socket(_In_ int af, _In_ int type, _In_ int protocol);
// int WSACleanup(void);
// int WSAStartup(_In_ WORD wVersionRequested, _Out_ LPWSADATA lpWSAData);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: microsoft linker (14.10)
// Detected functions: 4
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-09-06 08:24:48
